Update Readme to show usage more clearly
I ran into two issues when getting setup:

```
$ prisma db push
…
Running generate... (Use --skip-generate to skip the generators)
Error: Generator at zod-prisma-types could not start:

/bin/sh: zod-prisma-types: command not found
```
which is fixed by the npx command, clearly this isn't the universal way to do this, but i thought this PR would get it started

and it took me a few min to figure out how to import the schema...